spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/javaspringclub?serverTimezone=UTC
    username: root
    password: 1234
    
---
spring.jpa: 
  hibernate: 
    connection: 
      charset: utf8
      useUnicode: true
    ddl-auto: update
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  properties.hibernate.id.new_generator_mappings: false
  properties.hibernate.format_sql: true

  

  